### ISSUE TITLE
Which value is assigned to the environmental variable DB_PATH?

### ISSUE THREAD

**Issue by delta-kor** [CatHandRuler/nekomimi#1]
[nekomimi/src/client/EarthquateClient.js : 28](https://github.com/CatHandRuler/nekomimi/blob/main/src/client/EarthquakeClient.js#L28)
```javascript
    this.database = new sqlite3.Database(DB_PATH, (err) => {
                                         ^^^^^^^
```

Will the sqlite database address be assigned to environment variable DB_PATH?
If so, what format should I set it up in?

**Comment by CatHandRuler** [comment]
DB_PATH is not an environment variable, and your database file should be located at your-path/db and should be named in "guild-settings.db".
